plugins {
    id 'com.android.application'
}

android {
    namespace 'com.fondosstream.controller'
    compileSdk 34

    defaultConfig {
        applicationId "com.fondosstream.controller"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    // Android nativo sin librerías pesadas
}
